import Foundation

/// Closed portable projection, in dependency order. Paths, thumbnails and local
/// avatar references are intentionally absent. Foreign keys travel as UUIDs.
nonisolated struct SyncTable: Sendable, Equatable {
    let name: String
    let columns: [String]
    let integers: Set<String>
    let reals: Set<String>
    let naturalKey: [String]
    let references: [String: String]

    static let all: [SyncTable] = [
        SyncTable(name: "profile_documents",
            columns: ["document_json"],
            integers: [], reals: [],
            naturalKey: [], references: [:]),
        SyncTable(name: "wizard_lessons",
            columns: ["text", "pinned", "evidence", "created_at", "updated_at", "provider", "model", "learned_id"],
            integers: ["pinned"], reals: [],
            naturalKey: [], references: [:]),
        SyncTable(name: "people",
            columns: ["key", "name", "descriptor", "created_at", "category", "hidden"],
            integers: ["hidden"], reals: [],
            naturalKey: ["key"], references: [:]),
        SyncTable(name: "text_overlay_presets",
            columns: ["name", "data_json", "created_at"],
            integers: [], reals: [],
            naturalKey: ["name", "data_json"], references: [:]),
        SyncTable(name: "library_asset_metadata",
            columns: ["kind", "is_broll", "subjects_json", "tags_json", "provider", "model", "analyzed_at", "display_name", "placements_json", "technique", "asset_id"],
            integers: ["is_broll"], reals: [],
            naturalKey: ["asset_id"], references: [:]),
        SyncTable(name: "ig_accounts",
            columns: ["username", "kind", "display_name", "ig_user_id", "followers", "last_fetched_at", "added_at"],
            integers: ["followers"], reals: [],
            naturalKey: ["username"], references: [:]),
        SyncTable(name: "ig_media",
            columns: ["account_id", "media_id", "media_type", "caption", "permalink", "posted_at", "duration", "stats_json", "source", "fetched_at"],
            integers: ["account_id"], reals: ["duration"],
            naturalKey: ["account_id", "media_id"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "ig_report_media",
            columns: ["account_id", "media_id", "shortcode", "media_type", "media_product_type", "caption", "caption_truncated", "permalink", "posted_at", "like_count", "comments_count", "thumbnail_url", "source", "fetched_at"],
            integers: ["account_id", "caption_truncated", "like_count", "comments_count"], reals: [],
            naturalKey: ["account_id", "shortcode"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "taste_studies",
            columns: ["media_id", "category_key", "studied_at"],
            integers: ["media_id"], reals: [],
            naturalKey: ["media_id"], references: ["media_id": "ig_media"]),
        SyncTable(name: "ig_templates",
            columns: ["media_id", "template_json", "provider", "model", "analyzed_at"],
            integers: ["media_id"], reals: [],
            naturalKey: ["media_id"], references: ["media_id": "ig_media"]),
        SyncTable(name: "ig_account_snapshots",
            columns: ["account_id", "snapshot_date", "followers_count", "follows_count", "media_count", "source"],
            integers: ["account_id", "followers_count", "follows_count", "media_count"], reals: [],
            naturalKey: ["account_id", "snapshot_date"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "ig_media_insight_snapshots",
            columns: ["report_media_id", "metric", "value", "fetched_at", "source"],
            integers: ["report_media_id"], reals: ["value"],
            naturalKey: ["report_media_id", "metric", "fetched_at"], references: ["report_media_id": "ig_report_media"]),
        SyncTable(name: "ig_account_insights",
            columns: ["account_id", "metric", "period", "breakdown_dimension", "breakdown_value", "value", "end_time", "source"],
            integers: ["account_id"], reals: ["value"],
            naturalKey: ["account_id", "metric", "period", "breakdown_dimension", "breakdown_value", "end_time"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "ig_audience_demographics",
            columns: ["account_id", "metric", "dimension", "dimension_value", "timeframe", "value", "fetched_date", "source"],
            integers: ["account_id", "value"], reals: [],
            naturalKey: ["account_id", "metric", "dimension", "dimension_value", "timeframe", "fetched_date"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "ig_comments",
            columns: ["id", "account_id", "report_media_id", "parent_comment_id", "username", "from_id", "text", "like_count", "hidden", "timestamp", "ref_timestamp", "fetched_at"],
            integers: ["account_id", "report_media_id", "like_count", "hidden"], reals: [],
            naturalKey: ["id"], references: ["account_id": "ig_accounts", "report_media_id": "ig_report_media"]),
        SyncTable(name: "ig_commenter_rankings_import",
            columns: ["account_id", "period_key", "as_of", "username", "rank", "score", "early", "text_comments", "emoji_comments", "text_replies", "emoji_replies", "total"],
            integers: ["account_id", "rank", "score", "early", "text_comments", "emoji_comments", "text_replies", "emoji_replies", "total"], reals: [],
            naturalKey: ["account_id", "period_key", "username"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "ig_commenter_activity_import",
            columns: ["account_id", "period_key", "as_of", "username", "comments", "replies", "total", "top_posts_json"],
            integers: ["account_id", "comments", "replies", "total"], reals: [],
            naturalKey: ["account_id", "period_key", "username"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "ig_comment_heatmap_import",
            columns: ["account_id", "window_end", "dow", "hour", "count"],
            integers: ["account_id", "dow", "hour", "count"], reals: [],
            naturalKey: ["account_id", "window_end", "dow", "hour"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "ig_reel_analysis_import",
            columns: ["account_id", "report_media_id", "analysis_date", "score", "tier", "good_json", "bad_json", "top_tip"],
            integers: ["account_id", "report_media_id", "score"], reals: [],
            naturalKey: ["account_id", "report_media_id", "analysis_date"], references: ["account_id": "ig_accounts", "report_media_id": "ig_report_media"]),
        SyncTable(name: "ig_ignored_accounts",
            columns: ["account_id", "username", "reason"],
            integers: ["account_id"], reals: [],
            naturalKey: ["account_id", "username"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "ig_report_sync_state",
            columns: ["account_id", "key", "value"],
            integers: ["account_id"], reals: [],
            naturalKey: ["account_id", "key"], references: ["account_id": "ig_accounts"]),
        SyncTable(name: "reel_traits",
            columns: ["video_kind", "video_id", "version", "traits_json", "computed_at", "reference"],
            integers: ["version", "reference"], reals: [],
            naturalKey: ["video_kind", "video_id"], references: [:]),
        SyncTable(name: "reel_outcomes",
            columns: ["video_id", "account_id", "traits_version", "outcome_json"],
            integers: ["account_id", "traits_version"], reals: [],
            naturalKey: ["video_id"], references: ["account_id": "ig_accounts", "video_id": "ig_report_media"])
    ] + footage
    /// Independent runs retain a random run_key even when their timestamps match.
    static let footage: [SyncTable] = [
        SyncTable(name: "videos",
            columns: ["hash", "filename", "duration", "width", "height", "wide", "discovered_at", "analyzed_at", "podcast_layout", "podcast_seam_x", "podcast_layout_confidence", "podcast_tiles_json", "created_at", "drive_file_id", "drive_link", "analyzer_provider", "visual_analyzer_provider", "speech_analyzer_provider", "analyzer_model", "visual_analyzer_model", "speech_analyzer_model", "visual_analyzed_at", "speech_analyzed_at", "video_type", "naming_provider", "naming_model", "people_provider", "people_model", "people_detected_at", "speech_seconds", "people_seconds"],
            integers: ["width", "height", "wide"], reals: ["duration", "podcast_seam_x", "podcast_layout_confidence", "speech_seconds", "people_seconds"],
            naturalKey: ["hash"], references: [:]),
        SyncTable(name: "analysis_runs",
            columns: ["video_id", "name", "instructions", "provider", "model", "has_transcript", "sample_interval", "notes_json", "created_at", "settings_json", "models_json", "run_key"],
            integers: ["video_id", "has_transcript"], reals: ["sample_interval"],
            naturalKey: ["video_id", "created_at", "run_key"], references: ["video_id": "videos"]),
        SyncTable(name: "scenes",
            columns: ["video_id", "run_id", "start_time", "end_time", "excluded", "ignored", "favorite", "favorite_provider", "favorite_model", "crop_x_frac", "free_crops", "curated", "edit_start", "edit_end", "narrative", "score", "excitement", "parent_scene_id", "models_json", "curated_provider", "curated_model", "stack_choice"],
            integers: ["video_id", "run_id", "excluded", "ignored", "favorite", "curated", "parent_scene_id", "stack_choice"], reals: ["start_time", "end_time", "crop_x_frac", "edit_start", "edit_end", "score", "excitement"],
            naturalKey: ["video_id", "run_id", "start_time", "end_time"], references: ["video_id": "videos", "run_id": "analysis_runs", "parent_scene_id": "scenes"]),
        SyncTable(name: "scene_tags",
            columns: ["scene_id", "tag"],
            integers: ["scene_id"], reals: [],
            naturalKey: ["scene_id", "tag"], references: ["scene_id": "scenes"]),
        SyncTable(name: "moments",
            columns: ["video_id", "at_time", "note", "dialog"],
            integers: ["video_id"], reals: ["at_time"],
            naturalKey: [], references: ["video_id": "videos"]),
        SyncTable(name: "transcripts",
            columns: ["transcription_key", "transcription_created_at", "video_id", "language", "is_translation", "start_time", "end_time", "text", "provider", "model", "original_text", "words", "technique", "seconds", "speaker_key"],
            integers: ["video_id", "is_translation"], reals: ["start_time", "end_time", "seconds"],
            naturalKey: ["video_id", "transcription_key", "language", "is_translation", "start_time"], references: ["video_id": "videos"]),
        SyncTable(name: "speaker_turns",
            columns: ["transcription_key", "transcription_created_at", "video_id", "start_time", "end_time", "cluster", "confidence", "picture_side", "picture_confidence", "resolved_side", "person_key", "tile"],
            integers: ["video_id", "cluster", "tile"], reals: ["start_time", "end_time", "confidence", "picture_confidence"],
            naturalKey: ["video_id", "transcription_key", "start_time"], references: ["video_id": "videos"]),
        SyncTable(name: "transcript_features",
            columns: ["video_id", "start_time", "end_time", "text", "speaker_key", "energy", "kind"],
            integers: ["video_id"], reals: ["start_time", "end_time", "energy"],
            naturalKey: ["video_id", "start_time", "end_time", "kind"], references: ["video_id": "videos"]),
        SyncTable(name: "topic_ranges",
            columns: ["video_id", "title", "start_time", "end_time", "summary", "speaker_keys_json"],
            integers: ["video_id"], reals: ["start_time", "end_time"],
            naturalKey: ["video_id", "start_time", "end_time"], references: ["video_id": "videos"]),
        SyncTable(name: "video_people",
            columns: ["video_id", "person_id", "portrait_at", "portrait_json", "ranges_json", "detected_at"],
            integers: ["video_id", "person_id"], reals: ["portrait_at"],
            naturalKey: ["video_id", "person_id"], references: ["video_id": "videos", "person_id": "people"]),
        SyncTable(name: "person_markers",
            columns: ["video_id", "at_time", "x", "y", "width", "height", "person_id", "ignored", "created_at"],
            integers: ["video_id", "person_id", "ignored"], reals: ["at_time", "x", "y", "width", "height"],
            naturalKey: [], references: ["video_id": "videos", "person_id": "people"]),
        SyncTable(name: "video_subjects",
            columns: ["video_id", "name", "color_index", "rects_json", "created_at"],
            integers: ["video_id", "color_index"], reals: [],
            naturalKey: [], references: ["video_id": "videos"]),
        SyncTable(name: "video_notes",
            columns: ["video_id", "at_time", "note", "created_at", "provider", "model"],
            integers: ["video_id"], reals: ["at_time"],
            naturalKey: [], references: ["video_id": "videos"]),
        SyncTable(name: "grades",
            columns: ["scene_id", "score", "graded_at"],
            integers: ["scene_id", "score"], reals: [],
            naturalKey: [], references: ["scene_id": "scenes"]),
        SyncTable(name: "fight_events",
            columns: ["video_id", "at_time", "fighter_key", "action", "points", "provider", "model"],
            integers: ["video_id"], reals: ["at_time", "points"],
            naturalKey: ["video_id", "at_time", "fighter_key", "action"], references: ["video_id": "videos"]),
        SyncTable(name: "fight_outcomes",
            columns: ["video_id", "run_id", "method", "winner_key", "loser_key", "event", "round", "created_at"],
            integers: ["video_id", "run_id", "round"], reals: [],
            naturalKey: ["video_id", "run_id", "method", "winner_key", "loser_key"], references: ["video_id": "videos", "run_id": "analysis_runs"]),
        SyncTable(name: "fight_research",
            columns: ["video_id", "fight_label", "event", "fight_date", "summary_json", "sources_json", "provider", "model", "researched_at"],
            integers: ["video_id"], reals: [],
            naturalKey: ["video_id"], references: ["video_id": "videos"]),
        SyncTable(name: "wizard_research",
            columns: ["topic", "result_json", "researched_at", "provider", "model"],
            integers: [], reals: [],
            naturalKey: [], references: [:])
    ]
    var preservesDuplicateKeys: Bool {
        ["transcripts", "speaker_turns", "transcript_features", "topic_ranges", "fight_events", "fight_outcomes"].contains(name)
    }
    static var lessons: SyncTable { all.first { $0.name == "wizard_lessons" }! }
    static func named(_ name: String) throws -> SyncTable {
        guard let table = all.first(where: { $0.name == name }) else { throw SyncError.invalidRow("table") }
        return table
    }
}
